version: '2'

services:
  gitlab_web:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab_web
    restart: always
    hostname: '${GL_HOSTNAME}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${GL_HOSTNAME}'
        # Add any other gitlab.rb configuration here, each on its own line
      GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN: ${GL_CI_REG_TOKEN}
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
  gitlab_runner:
    image: 'gitlab/gitlab-runner:latest'
    network_mode: "host"
    container_name: gitlab_runner
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './gitlab-runner/config:/etc/gitlab-runner'